version: '3.9'

services:
    typesense:
        image: typesense/typesense:0.21.0
        environment:
            API_KEY: ${TYPESENSE_API_KEY}
        entrypoint: sh -c "/opt/typesense-server --data-dir /data --api-key=$${TYPESENSE_API_KEY} --enable-cors"
        ports:
            - 8108:8108
        volumes:
            - typesense-data:/data
        
    ai-sdk:
        build: .
        ports:
            - 8050:8050
        depends_on:
            - typesense
        environment:
            - .env
        restart: unless-stopped




volumes:
    typesense-data: