name: "ai-sdk-action"
description: "Merge Json Files"
author: "Kevin"
branding:
  icon: 'database'
  color: 'gray-dark'
inputs:
  merge_strategy:
    description: "Select Merge strategy (overwrite, version, objectMerge)"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"


