# This workflow will build and push a new container image to Dockerhub,
# and then will deploy a new image to Heroku, when a new committed is made to main branch
#
# To use this workflow, you will need to complete the following set-up steps:

name: ci

on:
  push:
    branches:
      - main
      - development

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 0research/ai-sdk:latest